src/webfaf/blueprints/celery_tasks.py
import json
from flask import (Blueprint, request, abort, render_template, flash,
                   redirect, url_for)
from wtforms import (Form,
                     validators,
                     SelectMultipleField,
                     StringField,
                     SelectField,
                     BooleanField,
                     TextAreaField,
                     FileField,
                     ValidationError)

from pyfaf.storage import (ExternalFafInstance, PeriodicTask, TaskResult, OpSys, OpSysRelease, Repo, Arch)
from pyfaf.celery_tasks import run_action, celery_app
from pyfaf.actions import actions as actions_all
from pyfaf.problemtypes import problemtypes
from pyfaf.opsys import systems
from pyfaf.bugtrackers import bugtrackers
from pyfaf.solutionfinders import solution_finders

from webfaf_main import db
from webfaf.forms import TagListField
from webfaf.utils import Pagination, admin_required

url_prefix = "/celery_tasks"

celery_tasks = Blueprint("celery_tasks", __name__)

# Filter actions to exclude cmdline_only ones
actions = dict()
for n, a in actions_all.items():
    if not a.cmdline_only:
        actions[n] = a


@celery_tasks.route("/")
@admin_required
def index():
    inspect = celery_app.control.inspect()
    pts = db.session.query(PeriodicTask).order_by(PeriodicTask.id).all()
    trs = (db.session.query(TaskResult)
           .order_by(TaskResult.finished_time.desc())
           .limit(20).all())
    return render_template("celery_tasks/index.html",
                           periodic_tasks=pts,
                           task_results=trs,
                           inspect_active=inspect.active() or {},
                           inspect_scheduled=inspect.scheduled() or {},
                           actions=sorted(actions.keys()))


@celery_tasks.route("/results/<result_id>/")
@admin_required
def results_item(result_id):
    tr = db.session.query(TaskResult).get(result_id)
    if tr is None:
        raise abort(404)

    return render_template("celery_tasks/results_item.html",
                           task_result=tr)


class ActionFormArgparser():
    def __init__(self, F):
        self.F = F
        self.prefix_chars = "-"

    # Adapted from argparse._ActionsContainer
    # Steven J. Bethard <steven.bethard@gmail.com>
    # Licensed under the Python license
    def _get_positional_kwargs(self, dest, **kwargs):
        # make sure required is not specified
        if 'required' in kwargs:
            msg = "'required' is an invalid argument for positionals"
            raise TypeError(msg)

        # return the keyword arguments with no option strings
        return dict(kwargs, dest=dest, option_strings=[])

    # Adapted from argparse._ActionsContainer
    # Steven J. Bethard <steven.bethard@gmail.com>
    # Licensed under the Python license
    def _get_optional_kwargs(self, *args, **kwargs):
        # determine short and long option strings
        option_strings = []
        long_option_strings = []
        for option_string in args:
            # error on strings that don't start with an appropriate prefix
            if not option_string[0] in self.prefix_chars:
                msg = 'invalid option string %r: must start with a character %r'
                tup = option_string, self.prefix_chars
                raise ValueError(msg % tup)

            # strings starting with two prefix characters are long options
            option_strings.append(option_string)
            if option_string[0] in self.prefix_chars:
                if len(option_string) > 1:
                    if option_string[1] in self.prefix_chars:
                        long_option_strings.append(option_string)

        # infer destination, '--foo-bar' -> 'foo_bar' and '-x' -> 'x'
        dest = kwargs.pop('dest', None)
        if dest is None:
            if long_option_strings:
                dest_option_string = long_option_strings[0]
            else:
                dest_option_string = option_strings[0]
            dest = dest_option_string.lstrip(self.prefix_chars)
            if not dest:
                msg = 'dest= is required for options like %r'
                raise ValueError(msg % dest_option_string)
            dest = dest.replace('-', '_')

        # return the updated keyword arguments
        return dict(kwargs, dest=dest, option_strings=option_strings)

    def add_argument(self, *args, **kwargs):
        if not args or len(args) == 1 and args[0][0] not in self.prefix_chars:
            kwargs = self._get_positional_kwargs(*args, **kwargs)
        else:
            kwargs = self._get_optional_kwargs(*args, **kwargs)

        action = kwargs.get("action", "store")
        field_args = (kwargs["dest"],)
        field_kwargs = dict(
            description=kwargs.get("help"),
            default=kwargs.get("default"),
            validators=[]
        )
        if action == "store_true":
            setattr(self.F, kwargs["dest"],
                    BooleanField(*field_args, **field_kwargs))
        else:
            if kwargs.get("validators"):
                for (vld, vld_kwargs) in kwargs.get("validators"):
                    vld_class = getattr(validators, vld)
                    field_kwargs["validators"].append(vld_class(**vld_kwargs))
            else:
                field_kwargs["validators"].append(validators.Optional())

            if kwargs.get("nargs", "?") in "+*" or action == "append":
                field_kwargs["description"] = ((field_kwargs.get("description") or "") +
                                               " Separate multiple values by comma ','.")
                setattr(self.F, kwargs["dest"],
                        TagListField(*field_args, **field_kwargs))
            else:
                setattr(self.F, kwargs["dest"],
                        StringField(*field_args, **field_kwargs))

        self.F.argparse_fields[kwargs["dest"]] = kwargs

    def add_argument_group(self):
        return ActionFormArgGroup(self.F)

    def add_opsys(self, multiple=False, required=False, positional=False, with_rel=False, helpstr=None): # pylint: disable=unused-argument
        if required:
            vs = [validators.Required()]
        else:
            vs = [validators.Optional()]

        choice_lst = [(osplugin.name, osplugin.nice_name) for osplugin in systems.values()]
        arg_str = "opsys"

        if positional:
            arg_str = "OPSYS"

            q = db.session.query(OpSys.name)
            choice_lst = [(a[0], a[0]) for a in q]

            if with_rel:
                q = q.join(OpSysRelease).with_entities(OpSys.name, OpSysRelease.version)
                choice_lst = [(a[0] + " " + a[1], a[0] + " " + a[1]) for a in q]

        Field = SelectField
        if multiple:
            Field = SelectMultipleField
        field = Field(
            "Operating System",
            vs,
            choices=choice_lst)
        setattr(self.F, arg_str, field)
        self.F.argparse_fields[arg_str] = {}

    def add_opsys_rel_status(self, required=False):
        if required:
            vs = [validators.Required()]
        else:
            vs = [validators.Optional()]

        field = SelectField(
            "Release status",
            vs,
            choices=[(a, a) for a in ["ACTIVE", "UNDER_DEVELOPMENT", "EOL"]])
        setattr(self.F, "status", field)
        self.F.argparse_fields["status"] = {}

    def add_arch(self, multiple=False, required=False, positional=False, helpstr=None): # pylint: disable=unused-argument
        if required:
            vs = [validators.Required()]
        else:
            vs = [validators.Optional()]

        arg_str = "arch"
        if positional:
            arg_str = "ARCH"

        Field = SelectField
        if multiple:
            Field = SelectMultipleField

        q = db.session.query(Arch.name).order_by(Arch.name)

        field = Field(
            "Architecture",
            vs,
            choices=[(a[0], a[0]) for a in q])
        setattr(self.F, arg_str, field)
        self.F.argparse_fields[arg_str] = {}

    def add_problemtype(self, multiple=False):
        Field = SelectField
        if multiple:
            Field = SelectMultipleField
        field = Field(
            "Problem type",
            choices=[(a, a) for a in sorted(problemtypes.keys())])
        setattr(self.F, "problemtype", field)
        self.F.argparse_fields["problemtype"] = {}

    def add_opsys_release(self, multiple=False, required=False, positional=False, helpstr=None): # pylint: disable=unused-argument
        if required:
            vs = [validators.Required()]
        else:
            vs = [validators.Optional()]

        Field = SelectField
        if multiple:
            Field = SelectMultipleField

        q = db.session.query(OpSysRelease.version).order_by(OpSysRelease.version)

        field = Field(
            "OS Release",
            vs,
            choices=[(a[0], a[0]) for a in q])

        arg_str = "opsys_release"
        if positional:
            arg_str = "RELEASE"

        setattr(self.F, arg_str, field)
        self.F.argparse_fields[arg_str] = {}

    def add_bugtracker(self, *args, **kwargs): # pylint: disable=unused-argument
        field = SelectField(
            "Bugtracker",
            choices=[(bt, bt) for bt in bugtrackers])
        setattr(self.F, "bugtracker", field)
        self.F.argparse_fields["bugtracker"] = {}

    def add_solutionfinder(self, *args, **kwargs): # pylint: disable=unused-argument
        field = SelectField(
            "Solution finder",
            choices=[(sf, sf) for sf in solution_finders])
        setattr(self.F, "solution_finder", field)
        self.F.argparse_fields["solution_finder"] = {}

    def add_repo(self, multiple=False, helpstr=None): # pylint: disable=unused-argument

        Field = SelectField
        if multiple:
            Field = SelectMultipleField

        q = db.session.query(Repo.name).order_by(Repo.name)

src/webfaf/templates/celery_tasks/action_run.html
{% extends "base.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Run or schedule action {{action_name}}{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-12">
      <h2>Run or schedule action {{action_name}}</h2>
    </div>
  </div>
  <div class="row">
    <form class="form" enctype="multipart/form-data" action="" method="POST">
      <div class="col-md-6">
        {% for field in action_form %}
            {{ render_field(field) }}
        {% else %}
          <p>This action requires no parameters.</p>
        {% endfor %}
        <p><button type="submit" class="btn btn-primary" name="run" value="run"><i class="fa fa-play-circle"></i>
 Run once</button></p>
      </div>
      <div class="col-md-6">
        {% for field in schedule_form %}
            {{ render_field(field) }}
        {% endfor %}
        <p><button type="submit" class="btn btn-primary" name="schedule" value="schedule"><i class="fa fa-plus"></i> Add to schedule</button></p>
      </div>
    </form>
  </div>
{% endblock %}

src/webfaf/templates/celery_tasks/index.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock %}

{% block js %}
{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-12">
    <h2>Run or schedule action</h2>
    <div class="three-columns">
      {% for a in actions %}
        <a href="{{url_for('celery_tasks.action_run', action_name=a)}}">{{a}}</a><br/>
      {% endfor %}
    </div>
    <h2>Running</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th><th>Task</th><th>Arguments</th>
        </tr>
      </thead>
      <tbody>
        {% for host,tasks in inspect_active.items() %}
          {% for task in tasks %}
            <tr>
              <td>{{task["id"]}}</td>
              <td>{{task["name"]}}</td>
              <td>{{task["args"]}}</td>
            </tr>  
          {% endfor %}
        {% endfor %}
      </tbody>
    </table>
    <h2>Queued</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th><th>Task</th><th>Arguments</th>
        </tr>
      </thead>
      <tbody>
        {% for host,tasks in inspect_scheduled.items() %}
          {% for task in tasks %}
            <tr>
              <td>{{task["id"]}}</td>
              <td>{{task["name"]}}</td>
              <td>{{task["args"]}}</td>
            </tr>  
          {% endfor %}
        {% endfor %}
      </tbody>
    </table>
    <h2>Schedule</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th><th>Name</th><th>Task</th><th>M</th><th>H</th><th>DoW</th><th>DoM</th><th>MoY</th>
        </tr>
      </thead>
      <tbody>
        {% for pt in periodic_tasks %}
          <tr>
            <td><a href="{{url_for('celery_tasks.schedule_item', pt_id=pt.id)}}">{{pt.id}}</a> {% if pt.enabled %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-ban"></i>{% endif %}</td>
            <td>{{pt.nice_name}}</td>
            <td>{{pt.nice_task}}</td>
            <td>{{pt.crontab_minute}}</td>
            <td>{{pt.crontab_hour}}</td>
            <td>{{pt.crontab_day_of_week}}</td>
            <td>{{pt.crontab_day_of_month}}</td>
            <td>{{pt.crontab_month_of_year}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <h2>Results</h2>
      <a href="{{url_for('celery_tasks.results_list')}}">All results</a>
      <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th><th>Task</th><th>Time</th><th>State</th>
        </tr>
      </thead>
      <tbody>
        {% for r in task_results %}
          <tr>
            <td><a href="{{url_for('celery_tasks.results_item', result_id=r.id)}}">{{r.id}}</a></td>
            <td>{{r.nice_task}}</td>
            <td>{{r.finished_time.strftime("%Y-%m-%d %H:%M:%S")}}</td>
            <td>{{r.state}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

src/webfaf/templates/celery_tasks/results_item.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock %}

{% block js %}
{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-12">
    <h2>Result {{task_result.id}}</h2>
    <dl class="dl-horizontal">
      <dt>Task</dt>
      <dd>{{task_result.nice_task}}</dd>
      <dt>Arguments</dt>
      <dd><pre>{{task_result.nice_args}}</pre></dd>
      <dt>Finished</dt>
      <dd>{{task_result.finished_time.strftime("%Y-%m-%d %H:%M:%S")}}</dd>
      <dt>State</dt>
      <dd>{{task_result.state}}</dd>
    </dl>
    <dl>
      <dt>Output</dt>
      <dd><pre>{{task_result.retval}}</pre><p>Only the last 1000 characters are saved.</p></dd>
    </dl>
  </div>
</div>
{% endblock %}

src/webfaf/templates/celery_tasks/results_list.html
{% extends "base.html" %}
{% from "_helpers.html" import paginator %}

{% block title %}Task results{% endblock %}

{% block js %}
{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-12">
    <h2>Task results</h2>
      <a href="{{url_for('celery_tasks.results_list')}}?unsuccessful_only=true">Show only unsuccessful results</a>
      <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th><th>Task</th><th>Time</th><th>State</th>
        </tr>
      </thead>
      <tbody>
        {% for r in task_results %}
          <tr>
            <td><a href="{{url_for('celery_tasks.results_item', result_id=r.id)}}">{{r.id}}</a></td>
            <td>{{r.nice_task}}</td>
            <td>{{r.finished_time.strftime("%Y-%m-%d %H:%M:%S")}}</td>
            <td>{{r.state}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {{ paginator(pagination, task_results|length) }}
  </div>
</div>
{% endblock %}

src/webfaf/templates/celery_tasks/schedule_item.html
{% extends "base.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Schedule item {{pt_name}}{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-12">
      <h2>Schedule item {{pt_name}}</h2>
    </div>
  </div>
  <div class="row">
    <form class="form" enctype="multipart/form-data" action="" method="POST">
      {% if action_form %}
        <div class="col-md-6">
        {% for field in action_form %}
            {{ render_field(field) }}
        {% else %}
          <p>This action requires no parameters.</p>
        {% endfor %}
      </div>  
      {% endif %}
      <div class="col-md-6">
        {% for field in schedule_form %}
            {{ render_field(field) }}
        {% endfor %}
        <p>
          <button type="submit" class="btn btn-primary" name="schedule" value="schedule"><i class="fa fa-check"></i> Save</button>
          <button type="submit" class="btn btn-sm btn-danger pull-right" name="delete" value="delete"><i class="fa fa-trash-o"></i> Delete</button>
        </p>
      </div>
    </form>
  </div>
{% endblock %}